### ISSUE TITLE
I think you will like this :)

### ISSUE THREAD

**Issue by gaberilde** [SistemaRayoXP/VirtualMac#1]
Im gaberilde from Gabrielo
I have added and fixed lots of things in your project.
You can find my version with all the fixes here https://github.com/gaberilde/VirtualMac !

**Comment by SistemaRayoXP** [comment]
Thanks, I'll check it out. These last months I had no time to continue coding the project, that's why the development gap
I've just tried to open the project, and noted that it's written in VS 2017, but I'm writing it in VS 2008.
So I will install VS2017 later to check it further more

Two things to mention:
1- You can also make Pull requests (I'm not sure whether I disabled them or not)
2- I noted that you used the early and kind of buggy 0.3.1, which was the first conversion from VB6 to VB-NET. I've made advance in the 0.4.1 which you can check in the releases tab. Also, I will release a new one right now with ability to load a config file into a window (and possibly save it), so you could help me with that one.

Also, I'd love to work with you into this project, but I need to know if you want to collaborate with me in the making of this app. I've made the wiki, with goals and status  about what I want this to end into, so you can get an idea of what are my goals by making this frontend

Updated with right info & some grammar corrections

**Comment by gaberilde** [comment]
Hi yes i removed about all of the vb6 stuff myself by now
I have config saving and loading on my version and a lot of other stuff you can try it by going to the releases on my version
https://github.com/gaberilde/VirtualMac/releases
I will probably take a break for a couple of days or weeks since its around Christmas but then i will start coding more again then..
and i will be happy to help

**Comment by gaberilde** [comment]
Also you need to put all the files in the zip folder for the release to organise them.
Otherwise you have to download each file...

**Comment by SistemaRayoXP** [comment]
At the end it says "Source code.zip". This file is automatically created by GitHub, and it contains all the files, so you can download only certain files, or download all at once using that file

Edit: Noted that it works different that what I thought, I think I will reorganize the code as you suggested

Also I've checked your code, it's excellent. But there's one thing, I use now a different way of opening and saving files. Now the app directly opens the file as a Basilisk/SheepShaver/PearPC file, so instead of using a custom configuration file, I'm opening the files "as-is". But there's one improvement that a custom file can bring...

**Comment by SistemaRayoXP** [comment]
Please take this with the best intention
May I ask why didn't you "fixed" a newer version like the 0.4.1 or 0.5.1?

**Comment by gaberilde** [comment]
when i downloaded it the latest version wasnt that

**Comment by SistemaRayoXP** [comment]
To download a new version go to releases. I release there every new version of the source code

**Comment by gaberilde** [comment]
yeah i know i usually just download it from the main page that way i know im getting the absolute latest version.

**Comment by SistemaRayoXP** [comment]
You have a point there. I usually never update the main page source files. I think I will do it since the next release (0.6.1)

**Comment by gaberilde** [comment]
Hi i know its been ages since i checked this out how have you been getting along? made more progress i will be happy to help again recently i was so busy i couldent work on project so sorry about that
